########################################################################################################################
## NECONOMICON - https://github.com/viduc/neconomicon                                                                 ##
## This file is a part of NECONOMICON application                                                                     ##
########################################################################################################################
FROM postgres:16.4-alpine3.20

ENV LANG fr_FR.UTF-8
ENV LANGUAGE fr_FR:fr
ENV LC_ALL fr_FR.UTF-8

RUN apk add --update postgresql-contrib